[package]
name = "bigdecimal"
version = "0.0.10"
authors = ["Andrew Kubera"]
description = "Arbitrary percision decimal numbers"
documentation = "https://docs.rs/bigdecimal"
homepage = "https://github.com/akubera/bigdecimal-rs"
repository = "https://github.com/akubera/bigdecimal-rs"
keywords = ["mathematics", "numerics", "decimal", "arbitrary-precision", "floating-point"]
license = "MIT/Apache-2.0"

[dependencies]
num = { version = "0.1.40", default-features=false, features=["bigint"] }
num-traits = "0.1.40"
serde = { version = "1", optional = true }
derive-diff = { version = "0.2.5", optional = true }
struct-diff = { version = "0.2.3", optional = true }

[dev-dependencies.rand]
version = "0.3"

[dev-dependencies.serde_json]
version = "1"

[features]
diff = ["derive-diff", "struct-diff"]